version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/scripts.sh
      timeout: 300
      runas: root
