name: Print Hello 2

on: [push]

jobs:
  say-hello:
    runs-on: self-hosted   # ya 'ubuntu-latest' agar aap GitHub-hosted runner use kar rahe ho
    steps:
      - name: Print message
        run: echo "Hello from GitHub Actions!"
